<!-- NOTE: do not re-name this file!  It has to be called index.qmd -->

# Welcome to the handbook for LNN @ UCPH! {.unnumbered}
# [Click here to return to our lab website](https://lnn-ucph.github.io/)

::: callout-note
Note to lab members: this document is a work in progress and may change.
It is your responsibility to be familiar with the content, so you should review these policies regularly.
:::

## Our Research
We focuse on leveraging advanced imaging technologies and computational methods to study the human brain. 
We integrate neuroimaging data with neuroinformatics approaches to understand brain structure, function, and connectivity. 
Our research areas typically include the development and application of machine learning algorithms, image analysis techniques, and data integration methods to advance the field of neuroscience and improve clinical outcomes in neurology and psychiatry. 
Our work often involves interdisciplinary collaboration, bridging gaps between computational sciences and neuroscience.


## Lab Philosophy
This is a good place to put any information about overall lab philosophies.
For example, thoughts about open science, collaboration, publishing, and the role of science in the world.
