
# LNN@UCPH Lab philosophy

## Mission statement
The [Lab for Neuroimaging and Neuroinformatics (LNN) @ UCPH](https://lnn-ucph.github.io) focuses on leveraging advanced imaging technologies and computational methods to study the human brain. We integrate neuroimaging data with neuroinformatics approaches to understand brain structure, function, and connectivity. Our research areas typically include the development and application of machine learning algorithms, image analysis techniques, and data integration methods to advance the field of neuroscience and improve clinical outcomes in neurology and psychiatry. Our work often involves interdisciplinary collaboration, bridging gaps between computational sciences and neuroscience.

## Shared leadership
The LNN@UCPH is led by two senior researchers, [Assoc. Professor Melanie Ganz-Benjaminsen](https://sites.google.com/view/melanieganz/home) and [Asst. Professor Martin Nørgaard](https://mnoergaard.github.io/). We believe that good science and research is inherently interdisciplinary and that we can drive science further when we work and collaborate with others. Therefore we have chosen to lead the lab together - one of us focusing a bit more on neuroimaging and the other on neuroinformatics.

## Scientific Conduct

### Reproducibility
Enhancing the reproducibility of research is on eof the core values of the LNN@UCPH. We strive to ensure the reproducibility of our research, meaning that we provide all the necessary data and the computer codes to run the analysis we have performed again, re-creating the results (see the [Turing Way Handbook](https://book.the-turing-way.org/reproducible-research/overview/overview-definitions/) for more details). You can find resources to improve the reproducibility of your research in this lab handbook under the following sections.

### Research conduct
All persons involved in research in the LNN@UCPH and at UCPH (regardless of their professional level) must familiarise themselves with and abide by [UCPH’s Code of Conduct for Responsible Research](https://research.ku.dk/integrity/code-of-conduct/). The lab and UCPH takes research misconduct seriously and will not tolerate fabrication, falsification, deletion of data or plagiarism committed willfully, or under gross negligence in planning, performing, or reporting research.

### Authorship guidelines

In general, we follow the [University of Copenhagen Code for Authorship](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://praksisudvalget.ku.dk/english/rules_guide/Kodeks_for_forfatterskab_ENG_final.pdf&ved=2ahUKEwjJjYXQyO-QAxUTHRAIHX7dPCwQFnoECBwQAQ&usg=AOvVaw05IF9Vv3LktW1sMiqF5ldt). This closely aligns with the Vancouver guidelines and requires all co-authors to contribute to published work. Additionally, we encourage that conversations about positions in the author list and order should happen early on in the project. As projects develop, and new people get involved, this type of conversation might need to happen more than once. 
The student or postdoc driving a project should expect to be first author. However, if they hand off the project they may lose the first-authorship unless co-first is appropriate. In egneral, veryone who contributes meaningfully to a paper should be included and as long as they fufill the authorship guidelines.

## Lab environment

### Code of Conduct
It is important that everyone at the department treats each other with respect and empathy. That's why the Department of Computer Science (DIKU) at the University of Copenhagen has a Code of Conduct, which everyone must follow. These guidelines are designed to ensure that everyone feels included and equal.
Read the DIKU Code of Conduct [here](https://di.ku.dk/english/diversity-and-inclusion/Code_of_Conduct_EN.pdf).

### Work-Life balance 
It is expected that you check for e-mail updates during the week, but not in the evenings, holidays, or on the weekend. For emergencies please use the private email addresses or any other media that you have agreed with your supervisor on.
Following this rule for "life-work-balance", we should be aware not to expect any comments, reviews or other replies to any issue in the evening of the same day, on holidays or throughout weekends.

### Expectations of lab engagement
We expect all lab members to engage actively in the lab. While we don’t have standard lab meetings, since we are embedded in larger groups, we organize lab events and hackathons and we expect you to participate in them.

### Feedback
As a member of the LNN, we expect you to be interested in learning and improving how science is carried out, both professionally and personally. This involves being able to provide and receive feedback. This is something that we strive towards ourselves every day, however, if you think that we can do better at something, or the lab can work better or improve, please let us know. For example, if you think there is something that we are not providing, but we should, please let us know. We think that one should feel comfortable to be as open-minded as possible to grow as a scientist, and this involves providing constructive and respectful feedback. 

### Working remotely
Our lab is embedded in different institutions and in general we need to follow the rules set by them regarding working remotely. But in general we support working from home a day a week and also when you travel home in order to give you the possibility to avoid e.g. holiday traffic and reduce travel costs for you.

### Sickness, Health and Personal Emergencies
Stay at home and take care of yourself if you are sick. You owe it to yourself to get better and to others who should risk getting sick at work. Please notify your supervisor and reschedule meetings for another day.
We are actively trying to create a good work environment to prevent work-related stress. However, sometimes life happens, and you or other lab members will have emergencies that need to be attended to. The lab leadership will always try to help and provide resources, personally and professionally, so do not hesitate to reach out to us. For reporting sick days or emergency leave, please follow the rules set by your place of employment, either DIKU or NRU.

### Reporting facility management issues
If you have any facility management issues to report, such as a broken light, please follow the guidelines outlined on the [DIKU homepage](https://kunet.ku.dk/faculty-and-department/diku/work_environment_and_well-being/Pages/default.aspx) and the [NRU staff manual](https://nru.dk/index.php/allcategories?task=download.send&id=9:nru-staff-manual&catid=10) (necessitates login).

### Reporting other issues
In general, please always feel free to reach out to the lab leadership with any issues. 
If you want to report any other issues that relate to offensive behavior and do not want to invvolve lab leadership, then feel free to consult the [University of Copenhagen guidelines](https://kunet.ku.dk/employee-guide/Pages/HR/Offensive-behaviour.aspx). At NRU, follow procedures described in the [NRU staff manual](https://nru.dk/index.php/allcategories?task=download.send&id=9:nru-staff-manual&catid=10) (necessitates login).


## References 

Inspirations for this lab philosophy were taken from: 

- [Prof. Russ Poldrack – Poldracklab](https://www.poldracklab.org/labguide)
- [Prof. Henriette Autzen – Autzen group](https://www.hautzen.com/resources)
- [Dr. Kirstie Whitaker – Whitaker lab](https://whitaker-lab.netlify.app/)
